import Head from "next/head";
import HeroSection from "../components/day-1/HeroSection";
import Navbar from "../components/day-1/Navbar";
import Portofolio from "../components/day-2/Portfolio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Navigation using nextjs and tailwindcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <main>
        {/* <Navbar /> //day-1 is completed
        <HeroSection />  //day-1 is completed*/} 
        <Portofolio/>
      </main>
    </div>
  );
}
