import Head from "next/head";
import RandomEmoji from "../components/day-12/RandomEmoji";
import Feature from "../components/day-13/Feature";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Navigation using nextjs and tailwindcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
 <Feature/>
    
      
    </div>
  );
}
