import Head from "next/head";
import PageNotFound from "../components/day-7/PageNotFound";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Navigation using nextjs and tailwindcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <main className="h-screen w-screen flex justify-center items-center bg-black">
        <PageNotFound/>
      </main>
    </div>
  );
}
